### ISSUE TITLE
Handle FormData Object

### ISSUE THREAD

**Issue by cherifGsoul** [canjs/can-ajax#29]
It would be nice if we can handle [FormData](https://developer.mozilla.org/en-US/docs/Web/API/FormData), as an example: 
```js
import ajax from "can-ajax";

const formData = new FormData();
formData.append('foo','bar')
ajax({
 url: '/post-url',
 type: 'POST',
 data: formData
})
```

**Comment by justinbmeyer** [comment]
Yes, this would be great!

**Comment by pYr0x** [comment]
@cherifGsoul is that PR ready to merge?

**Comment by cherifGsoul** [comment]
@pYr0x yes it can be merged it was there for sometime waiting to be approved, @justinbmeyer approved it!

**Comment by phillipskevin** [comment]
I'll merge/release this on Monday. Nice work!
