### ISSUE TITLE
can-ajax and Headers

### ISSUE THREAD

**Issue by HTMLGhozt** [canjs/can-ajax#50]
At the moment can-ajax doesn't handle headers. This includes `can-ajax.ajaxSetup`

**Comment by DesignByOnyx** [comment]
The best way is to use the `beforeSend` callback. This should be a function which will receive the XHR object before the request is sent. From there, you can add anything you want to the underlying XHR object:

```js
ajax({
  url: '/foo/bar',
  beforeSend: function(xhr) {
    xhr.withCredentials = true;
    xhr.setRequestHeader('Authentication', 'Bearer abcdefg');
  }
};
```
