### ISSUE TITLE
support for multipart/form-data contentType

### ISSUE THREAD

**Issue by dbleier** [canjs/can-ajax#69]
Currently `can-ajax` only allows `application/json` or `application/x-www-form-urlencoded` content types.

However when trying to upload files and other form data, we need `multipart/form-data` which the correct boundary. The best way (and only that I have found) is not to set `Content-Type` at all and the browser will set it correctly.

I propose checking the contentType option for `multipart/form-data` and if so, then not setting `Content-Type` at all.

This is what I did in my local can until a fix comes out:
```js
if (o.contentType !== 'multipart/form-data') {
            // CORS simple: `Content-Type` has to be `application/x-www-form-urlencoded`:
            var setContentType = (isJsonContentType && !isSimpleCors) ?
                "application/json" : "application/x-www-form-urlencoded";
            xhr.setRequestHeader("Content-Type", setContentType);
}
```

**Comment by phillipskevin** [comment]
related to https://github.com/canjs/canjs/issues/5290.

**Comment by m-mujica** [comment]
So, `boundary` can be an arbitrary value, see https://stackoverflow.com/a/30194096

In this issue https://github.com/github/fetch/issues/505#issuecomment-293064470, the approach suggested is to not set the header and let `fetch` figure out the content type header based on the FormData object passed in as the request body.

Here is another relevant article discussing the same approach https://muffinman.io/uploading-files-using-fetch-multipart-form-data/.

I guess we could do the same thing in can-ajax, check the body and generate the right content type. 

https://github.com/github/fetch/blob/37d10362687492868548c4d70c5c12e4a671771e/test/test.js#L834-L846

**Comment by m-mujica** [comment]
ok, so the suggestion here is the same mentioned in the fetch issue. Not setting the content-type manually and let the browser set the boundary works.

I was able to replicate with the example code below (without setting the hearder manually the request does not fail):


```html
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta http-equiv="X-UA-Compatible" content="ie=edge" />
    <title>can-ajax multipart form-data issue</title>
  </head>
  <body>
    <label for="file">Choose a profile picture:</label>
    <input type="file" id="file" name="file" multiple="multiple" />
    <script type="module">
      import { ajax } from "//unpkg.com/can@5/core.mjs";

      document.querySelector("#file").addEventListener("change", () => {
        let fileInput = document.querySelector("#file");
        let formData = new FormData();
        formData.append("file", fileInput.files[0]);

        ajax({
          url: "http://127.0.0.1:3000/upload",
          type: "POST",
          data: formData
          // beforeSend(xhr) {
          //   xhr.setRequestHeader("Content-Type", "multipart/form-data");
          // }
        }).then(result => {
          console.log(result.data);
        });
      });
    </script>
  </body>
</html>
```

The server code:

```js
var cors = require("cors");
var express = require("express");
var formidable = require("formidable");

var app = express();
app.use(cors());

app.post("/upload", (req, res, next) => {
  var form = new formidable.IncomingForm();

  form.parse(req, function(err, fields, files) {
    if (err) {
      next(err);
    } else {
      res.json({ fields: fields, files: files });
    }
  });
});

module.exports = app;
```
