### ISSUE TITLE
Add can-ajax to canjs infrastructure

### ISSUE THREAD

**Issue by ashvinrai** [canjs/can-ajax#9]
can-ajax has no documentation for canjs v3

**Comment by phillipskevin** [comment]
If anyone would like to help with this, here are the steps that need to be completed to add `can-ajax` to the canjs build so the docs will show up correctly: https://canjs.com/doc/guides/contributing/adding-ecosystem-modules.html#IntegratebuildwithCanJS.

**Comment by phillipskevin** [comment]
These are added in `minor` with https://github.com/canjs/canjs/pull/3581.
